name: GoGit CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
      - name: test
        run: make test
